"""costo en items de presupuesto

Revision ID: 005881a5e72d
Revises: e323f152407b
Create Date: 2026-09-19 20:04:08.208666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005881a5e72d'
down_revision = 'e323f152407b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presupuesto_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costo_unitario', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presupuesto_item', schema=None) as batch_op:
        batch_op.drop_column('costo_unitario')

    # ### end Alembic commands ###
