"""ubicacion de repuestos

Revision ID: 01d09e4a6667
Revises: 82753857c412
Create Date: 2026-09-19 01:15:41.441593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d09e4a6667'
down_revision = '82753857c412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repuesto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estanteria', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('estante', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repuesto', schema=None) as batch_op:
        batch_op.drop_column('estante')
        batch_op.drop_column('estanteria')

    # ### end Alembic commands ###
