"""perfil de listas de precios

Revision ID: 0853f63a3ccb
Revises: 1b7f66199561
Create Date: 2026-09-19 21:01:40.089335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0853f63a3ccb'
down_revision = '1b7f66199561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfil_lista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.String(length=60), nullable=False),
    sa.Column('col_codigo', sa.String(length=120), nullable=True),
    sa.Column('col_marca', sa.String(length=120), nullable=True),
    sa.Column('col_precio', sa.String(length=120), nullable=False),
    sa.Column('col_envase', sa.String(length=120), nullable=True),
    sa.Column('campo_codigo', sa.String(length=20), nullable=True),
    sa.Column('factor', sa.Float(), nullable=True),
    sa.Column('equivalencias', sa.String(length=120), nullable=True),
    sa.Column('actualizada', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proveedor')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perfil_lista')
    # ### end Alembic commands ###
