"""porcentajes del reparto por mes

Revision ID: 23f47ac67ced
Revises: 43bfe155b17c
Create Date: 2026-09-20 14:23:59.624078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f47ac67ced'
down_revision = '43bfe155b17c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cierre_mensual', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pct_repago', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pct_ganancia', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cierre_mensual', schema=None) as batch_op:
        batch_op.drop_column('pct_ganancia')
        batch_op.drop_column('pct_repago')

    # ### end Alembic commands ###
