"""carpeta de circulares

Revision ID: 43bfe155b17c
Revises: ee5d2f7d0074
Create Date: 2026-09-20 13:58:10.297394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43bfe155b17c'
down_revision = 'ee5d2f7d0074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_taller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carpeta_circulares', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_taller', schema=None) as batch_op:
        batch_op.drop_column('carpeta_circulares')

    # ### end Alembic commands ###
