"""costo de lista

Revision ID: 49619c9f7ed4
Revises: a54350cd380a
Create Date: 2026-09-19 00:59:46.620398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49619c9f7ed4'
down_revision = 'a54350cd380a'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('repuesto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costo_lista', sa.Float(), nullable=False, server_default='0'))
    # El costo guardado era el final (con descuento): el de lista es el anterior al descuento
    op.execute("UPDATE repuesto SET costo_lista = CASE WHEN descuento_oferta > 0 AND descuento_oferta < 1 "
               "THEN precio_costo / (1 - descuento_oferta) ELSE precio_costo END")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repuesto', schema=None) as batch_op:
        batch_op.drop_column('costo_lista')

    # ### end Alembic commands ###
