"""origen de lo importado de la contable

Revision ID: 8256d7862b35
Revises: d922f22552e7
Create Date: 2026-09-20 13:38:08.176995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8256d7862b35'
down_revision = 'd922f22552e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aporte_capital', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origen', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_aporte_capital_origen'), ['origen'], unique=False)

    with op.batch_alter_table('movimiento_contable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origen', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_movimiento_contable_origen'), ['origen'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimiento_contable', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimiento_contable_origen'))
        batch_op.drop_column('origen')

    with op.batch_alter_table('aporte_capital', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aporte_capital_origen'))
        batch_op.drop_column('origen')

    # ### end Alembic commands ###
