"""fotos de repuestos y categorias

Revision ID: 82753857c412
Revises: 49619c9f7ed4
Create Date: 2026-09-19 01:12:08.337126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82753857c412'
down_revision = '49619c9f7ed4'
branch_labels = None
depends_on = None

# Categorías y subcategorías del taller (las de AppSheet)
CATEGORIAS = ["MOTOR", "FILTROS", "COMBUSTIBLE", "REFRIGERACION", "ENCENDIDO", "FRENOS", "SUSPENSION Y DIRECCION",
              "TRANSMISION", "ELECTRICO", "LUBRICANTES Y FLUIDOS", "ACCESORIOS", "VARIOS"]
SUBCATEGORIAS = {
    "MOTOR": ["CORREA POLY-V", "CORREA DISTRIBUCION", "DISTRIBUCION KIT", "TENSOR", "POLEA", "JUNTAS", "RETEN",
              "BULONERIA", "ARBOL DE LEVAS", "JUNTAS KIT", "SOPORTE MOTOR", "TAPONES"],
    "FILTROS": ["KIT", "ACEITE", "AIRE", "COMBUSTIBLE", "HABITACULO"],
    "COMBUSTIBLE": ["BOMBA DE COMBUSTIBLE", "FLOTANTE - INSTRUMENTO"],
    "REFRIGERACION": ["BOMBA DE AGUA", "RADIADOR", "TERMOSTATO", "DEPOSITO", "MANGUERA"],
    "ENCENDIDO": ["BUJIA", "BUJIA PRECALENTAMIENTO", "CABLES DE BUJIA", "BOBINA", "INYECTOR", "ACCESORIOS INYECCION",
                  "PASO A PASO"],
    "FRENOS": ["PASTILLAS", "DISCOS", "CINTAS", "BOMBA DE FRENO"],
    "SUSPENSION Y DIRECCION": ["AMORTIGUADOR", "BIELETA", "AXIAL", "ROTULA", "ESPIRAL", "PARRILLA", "CAZOLETA"],
    "TRANSMISION": ["EMBRAGUE", "TRICETA", "FUELLE", "RODAMIENTO", "SEMIEJE", "HOMOCINETICA"],
    "ELECTRICO": ["BATERIA", "ALTERNADOR", "BURRO DE ARRANQUE", "SENSOR", "LAMPARA"],
    "LUBRICANTES Y FLUIDOS": ["ACEITE MOTOR", "ACEITE TRANSMISION", "REFRIGERANTE", "LIQUIDO DE FRENOS",
                              "LIMPIAPARABRISAS", "AGUA DESMINERALIZADA", "ACEITE HIDRÁULICO"],
    "ACCESORIOS": ["ESCOBILLA"],
    "VARIOS": ["SERVICIO"],
}


def _cargar_categorias():
    conexion = op.get_bind()
    for nombre in CATEGORIAS:
        existe = conexion.execute(sa.text("SELECT id FROM categoria WHERE upper(nombre) = :n"), {"n": nombre}).scalar()
        if existe is None:
            conexion.execute(sa.text("INSERT INTO categoria (nombre) VALUES (:n)"), {"n": nombre})
    for categoria, subs in SUBCATEGORIAS.items():
        cat_id = conexion.execute(sa.text("SELECT id FROM categoria WHERE upper(nombre) = :n"), {"n": categoria}).scalar()
        for sub in subs:
            existe = conexion.execute(sa.text("SELECT id FROM subcategoria WHERE categoria_id = :c AND upper(nombre) = :n"),
                                      {"c": cat_id, "n": sub}).scalar()
            if existe is None:
                conexion.execute(sa.text("INSERT INTO subcategoria (nombre, categoria_id) VALUES (:n, :c)"),
                                 {"n": sub, "c": cat_id})


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foto_repuesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repuesto_id', sa.Integer(), nullable=False),
    sa.Column('archivo', sa.String(length=300), nullable=False),
    sa.Column('drive_id', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repuesto_id'], ['repuesto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    _cargar_categorias()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foto_repuesto')
    # ### end Alembic commands ###
