"""esquema inicial

Revision ID: a1749331c4e6
Revises: 
Create Date: 2026-09-18 22:05:58.276607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1749331c4e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('cuit', sa.String(length=20), nullable=True),
    sa.Column('condicion_iva', sa.String(length=40), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=False),
    sa.Column('actualizado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliente_nombre'), ['nombre'], unique=False)

    op.create_table('config_markup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.String(length=60), nullable=False),
    sa.Column('marca_envase', sa.String(length=60), nullable=True),
    sa.Column('markup', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_taller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor_hora', sa.Float(), nullable=False),
    sa.Column('razon_social', sa.String(length=120), nullable=True),
    sa.Column('cuit', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingreso_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('proveedor', sa.String(length=120), nullable=False),
    sa.Column('nro_factura', sa.String(length=40), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=False),
    sa.Column('actualizado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('subcategoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patente', sa.String(length=10), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=40), nullable=True),
    sa.Column('modelo', sa.String(length=60), nullable=True),
    sa.Column('motor', sa.String(length=40), nullable=True),
    sa.Column('traccion', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('kilometraje', sa.Integer(), nullable=True),
    sa.Column('vin', sa.String(length=30), nullable=True),
    sa.Column('ecu_marca', sa.String(length=40), nullable=True),
    sa.Column('ecu_modelo', sa.String(length=60), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=False),
    sa.Column('actualizado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehiculo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehiculo_patente'), ['patente'], unique=True)

    op.create_table('presupuesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('modo_mano_obra', sa.String(length=20), nullable=True),
    sa.Column('horas_mano_obra', sa.Float(), nullable=True),
    sa.Column('valor_hora', sa.Float(), nullable=True),
    sa.Column('monto_fijo_mo', sa.Float(), nullable=True),
    sa.Column('mostrar_precios_detalle', sa.Boolean(), nullable=True),
    sa.Column('archivo_pdf', sa.String(length=300), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=False),
    sa.Column('actualizado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repuesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('proveedor', sa.String(length=60), nullable=True),
    sa.Column('marca', sa.String(length=60), nullable=True),
    sa.Column('nro_parte', sa.String(length=60), nullable=True),
    sa.Column('codigo_barras', sa.String(length=60), nullable=True),
    sa.Column('cod_proveedor', sa.String(length=60), nullable=True),
    sa.Column('marca_proveedor', sa.String(length=60), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('subcategoria_id', sa.Integer(), nullable=True),
    sa.Column('stock_actual', sa.Float(), nullable=False),
    sa.Column('stock_minimo', sa.Float(), nullable=True),
    sa.Column('precio_costo', sa.Float(), nullable=False),
    sa.Column('costo_manual', sa.Boolean(), nullable=True),
    sa.Column('markup', sa.Float(), nullable=True),
    sa.Column('precio_venta', sa.Float(), nullable=False),
    sa.Column('descuento_oferta', sa.Float(), nullable=True),
    sa.Column('comp_marca', sa.String(length=60), nullable=True),
    sa.Column('comp_modelo', sa.String(length=120), nullable=True),
    sa.Column('comp_motor', sa.String(length=60), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('foto', sa.String(length=300), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=False),
    sa.Column('actualizado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['subcategoria_id'], ['subcategoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repuesto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repuesto_codigo_barras'), ['codigo_barras'], unique=False)
        batch_op.create_index(batch_op.f('ix_repuesto_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_repuesto_nro_parte'), ['nro_parte'], unique=False)

    op.create_table('turno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('vehiculo_id', sa.Integer(), nullable=True),
    sa.Column('contacto', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('duracion_valor', sa.Float(), nullable=True),
    sa.Column('duracion_unidad', sa.String(length=10), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=False),
    sa.Column('actualizado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turno', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turno_fecha'), ['fecha'], unique=False)

    op.create_table('ingreso_stock_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingreso_id', sa.Integer(), nullable=False),
    sa.Column('repuesto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ingreso_id'], ['ingreso_stock.id'], ),
    sa.ForeignKeyConstraint(['repuesto_id'], ['repuesto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orden_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('km_entrada', sa.Integer(), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('presupuesto_cliente', sa.Float(), nullable=True),
    sa.Column('total_cobrado', sa.Float(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('clasificacion_cierre', sa.String(length=40), nullable=True),
    sa.Column('km_proximo_service', sa.Integer(), nullable=True),
    sa.Column('link_reporte', sa.String(length=300), nullable=True),
    sa.Column('aceite_motor', sa.Boolean(), nullable=True),
    sa.Column('aceite_motor_detalle', sa.String(length=120), nullable=True),
    sa.Column('aceite_caja', sa.Boolean(), nullable=True),
    sa.Column('aceite_caja_detalle', sa.String(length=120), nullable=True),
    sa.Column('aceite_diferencial', sa.Boolean(), nullable=True),
    sa.Column('aceite_diferencial_detalle', sa.String(length=120), nullable=True),
    sa.Column('filtro_aceite', sa.Boolean(), nullable=True),
    sa.Column('filtro_aire', sa.Boolean(), nullable=True),
    sa.Column('filtro_habitaculo', sa.Boolean(), nullable=True),
    sa.Column('filtro_combustible', sa.Boolean(), nullable=True),
    sa.Column('scaneo', sa.Boolean(), nullable=True),
    sa.Column('otros', sa.Text(), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=False),
    sa.Column('actualizado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['turno_id'], ['turno.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presupuesto_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=False),
    sa.Column('repuesto_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuesto.id'], ),
    sa.ForeignKeyConstraint(['repuesto_id'], ['repuesto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presupuesto_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuesto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumo_ot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ot_id', sa.Integer(), nullable=False),
    sa.Column('repuesto_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('precio_costo', sa.Float(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['ot_id'], ['orden_trabajo.id'], ),
    sa.ForeignKeyConstraint(['repuesto_id'], ['repuesto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foto_ot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ot_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('archivo', sa.String(length=300), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ot_id'], ['orden_trabajo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro_horas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ot_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('mecanico', sa.String(length=60), nullable=False),
    sa.Column('horas', sa.Float(), nullable=False),
    sa.Column('detalle', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['ot_id'], ['orden_trabajo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarea_ot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ot_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['ot_id'], ['orden_trabajo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('ot_id', sa.Integer(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=30), nullable=True),
    sa.Column('tipo_comprobante', sa.String(length=10), nullable=True),
    sa.Column('link_comprobante', sa.String(length=300), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=False),
    sa.Column('actualizado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['ot_id'], ['orden_trabajo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venta_fecha'), ['fecha'], unique=False)

    op.create_table('movimiento_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('repuesto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('ot_id', sa.Integer(), nullable=True),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('ingreso_id', sa.Integer(), nullable=True),
    sa.Column('detalle', sa.String(length=300), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingreso_id'], ['ingreso_stock.id'], ),
    sa.ForeignKeyConstraint(['ot_id'], ['orden_trabajo.id'], ),
    sa.ForeignKeyConstraint(['repuesto_id'], ['repuesto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimiento_stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimiento_stock_fecha'), ['fecha'], unique=False)

    op.create_table('venta_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('repuesto_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['repuesto_id'], ['repuesto.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venta_item')
    with op.batch_alter_table('movimiento_stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimiento_stock_fecha'))

    op.drop_table('movimiento_stock')
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venta_fecha'))

    op.drop_table('venta')
    op.drop_table('tarea_ot')
    op.drop_table('registro_horas')
    op.drop_table('foto_ot')
    op.drop_table('consumo_ot')
    op.drop_table('presupuesto_trabajo')
    op.drop_table('presupuesto_item')
    op.drop_table('orden_trabajo')
    op.drop_table('ingreso_stock_item')
    with op.batch_alter_table('turno', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turno_fecha'))

    op.drop_table('turno')
    with op.batch_alter_table('repuesto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repuesto_nro_parte'))
        batch_op.drop_index(batch_op.f('ix_repuesto_nombre'))
        batch_op.drop_index(batch_op.f('ix_repuesto_codigo_barras'))

    op.drop_table('repuesto')
    op.drop_table('presupuesto')
    with op.batch_alter_table('vehiculo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehiculo_patente'))

    op.drop_table('vehiculo')
    op.drop_table('subcategoria')
    op.drop_table('usuario')
    op.drop_table('ingreso_stock')
    op.drop_table('config_taller')
    op.drop_table('config_markup')
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_nombre'))

    op.drop_table('cliente')
    op.drop_table('categoria')
    # ### end Alembic commands ###
