"""fotos reporte taller drive

Revision ID: a54350cd380a
Revises: 10247bcec340
Create Date: 2026-09-19 00:30:26.074177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54350cd380a'
down_revision = '10247bcec340'
branch_labels = None
depends_on = None


def upgrade():
    # 1) columnas nuevas (con valor por defecto para las filas existentes)
    with op.batch_alter_table('foto_ot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('en_reporte', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('en_taller', sa.Boolean(), nullable=False, server_default=sa.false()))
    # 2) el tipo viejo pasa a las marcas nuevas
    fotos = sa.table('foto_ot', sa.column('tipo', sa.String), sa.column('en_reporte', sa.Boolean),
                     sa.column('en_taller', sa.Boolean))
    op.execute(fotos.update().where(fotos.c.tipo == 'taller').values(en_reporte=False, en_taller=True))
    # 3) se quita la columna vieja
    with op.batch_alter_table('foto_ot', schema=None) as batch_op:
        batch_op.drop_column('tipo')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto_ot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(length=20), nullable=True))
    fotos = sa.table('foto_ot', sa.column('tipo', sa.String), sa.column('en_reporte', sa.Boolean))
    op.execute(fotos.update().values(tipo='reparacion'))
    op.execute(fotos.update().where(fotos.c.en_reporte == sa.false()).values(tipo='taller'))
    with op.batch_alter_table('foto_ot', schema=None) as batch_op:
        batch_op.drop_column('en_taller')
        batch_op.drop_column('en_reporte')
        batch_op.drop_column('drive_id')

    # ### end Alembic commands ###
