"""Condiciones de pago: cuánto descuenta la tarjeta y cuándo acredita

Revision ID: a5a932514562
Revises: 23f47ac67ced
Create Date: 2026-09-20 19:55:58.632128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a932514562'
down_revision = '23f47ac67ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condicion_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=40), nullable=False),
    sa.Column('dias_habiles', sa.Integer(), nullable=False),
    sa.Column('arancel', sa.Float(), nullable=False),
    sa.Column('tasa_financiera', sa.Float(), nullable=False),
    sa.Column('iva', sa.Float(), nullable=False),
    sa.Column('recargo', sa.Float(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condicion_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bruto_cobrado', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('neto_acreditado', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fecha_acreditacion', sa.Date(), nullable=True))
        batch_op.create_foreign_key('fk_venta_condicion', 'condicion_pago', ['condicion_id'], ['id'])

    # Las de Getnet, plazo estándar (getnet.net/ar/aranceles). Se editan en Configuración.
    op.bulk_insert(
        sa.table('condicion_pago',
                 sa.column('nombre', sa.String), sa.column('dias_habiles', sa.Integer),
                 sa.column('arancel', sa.Float), sa.column('tasa_financiera', sa.Float),
                 sa.column('iva', sa.Float), sa.column('activa', sa.Boolean), sa.column('orden', sa.Integer)),
        [{'nombre': n, 'dias_habiles': d, 'arancel': a, 'tasa_financiera': t,
          'iva': 21.0, 'activa': True, 'orden': i}
         for i, (n, d, a, t) in enumerate([
             ('Efectivo', 0, 0.0, 0.0),
             ('Transferencia', 0, 0.0, 0.0),
             ('Débito', 1, 1.00, 0.0),
             ('Crédito 1 pago', 8, 2.00, 0.0),
             ('Crédito 3 cuotas', 2, 2.00, 7.41),
             ('Crédito 6 cuotas', 2, 2.00, 12.64),
             ('Mercado Pago', 0, 0.0, 0.0),
         ])])

    # Las ventas que ya están quedan atadas a su condición por el nombre que tenían
    op.execute("update venta set condicion_id = (select id from condicion_pago c where c.nombre = venta.metodo_pago)")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_constraint('fk_venta_condicion', type_='foreignkey')
        batch_op.drop_column('fecha_acreditacion')
        batch_op.drop_column('neto_acreditado')
        batch_op.drop_column('bruto_cobrado')
        batch_op.drop_column('condicion_id')

    op.drop_table('condicion_pago')
    # ### end Alembic commands ###
