"""modulo de administracion

Revision ID: b8dae7241cc3
Revises: 2133716b5bb7
Create Date: 2026-09-20 13:04:48.704082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8dae7241cc3'
down_revision = '2133716b5bb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cierre_mensual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.String(length=7), nullable=False),
    sa.Column('fecha_cierre', sa.Date(), nullable=True),
    sa.Column('cotizacion', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('modo', sa.String(length=10), nullable=True),
    sa.Column('colchon', sa.Float(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mes')
    )
    op.create_table('socio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('rol', sa.String(length=60), nullable=True),
    sa.Column('sueldo_base', sa.Float(), nullable=True),
    sa.Column('participacion', sa.Float(), nullable=True),
    sa.Column('alias', sa.String(length=60), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('aporte_capital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('socio_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('pesos', sa.Float(), nullable=False),
    sa.Column('cotizacion', sa.Float(), nullable=True),
    sa.Column('notas', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['socio_id'], ['socio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aporte_capital', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aporte_capital_fecha'), ['fecha'], unique=False)

    op.create_table('movimiento_contable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('mes_imputacion', sa.String(length=7), nullable=False),
    sa.Column('clasificacion', sa.String(length=40), nullable=True),
    sa.Column('comprobante', sa.String(length=20), nullable=True),
    sa.Column('nro_comprobante', sa.String(length=40), nullable=True),
    sa.Column('quien', sa.String(length=120), nullable=True),
    sa.Column('cuit', sa.String(length=15), nullable=True),
    sa.Column('concepto', sa.String(length=300), nullable=True),
    sa.Column('neto', sa.Float(), nullable=True),
    sa.Column('iva', sa.Float(), nullable=True),
    sa.Column('percepciones', sa.Float(), nullable=True),
    sa.Column('no_gravado', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('cobrado', sa.Boolean(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('ingreso_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingreso_id'], ['ingreso_stock.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimiento_contable', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimiento_contable_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimiento_contable_mes_imputacion'), ['mes_imputacion'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimiento_contable', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimiento_contable_mes_imputacion'))
        batch_op.drop_index(batch_op.f('ix_movimiento_contable_fecha'))

    op.drop_table('movimiento_contable')
    with op.batch_alter_table('aporte_capital', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aporte_capital_fecha'))

    op.drop_table('aporte_capital')
    op.drop_table('socio')
    op.drop_table('cierre_mensual')
    # ### end Alembic commands ###
