"""forma del archivo de la lista de precios

Revision ID: c308a1a344f8
Revises: 0853f63a3ccb
Create Date: 2026-09-19 21:14:57.735354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c308a1a344f8'
down_revision = '0853f63a3ccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil_lista', schema=None) as batch_op:
        batch_op.add_column(sa.Column('columnas', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('filas', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil_lista', schema=None) as batch_op:
        batch_op.drop_column('filas')
        batch_op.drop_column('columnas')

    # ### end Alembic commands ###
