"""proveedores

Revision ID: e323f152407b
Revises: 01d09e4a6667
Create Date: 2026-09-19 01:16:36.197398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e323f152407b'
down_revision = '01d09e4a6667'
branch_labels = None
depends_on = None


PROVEEDORES = ["Carlitos Peugeot", "FGC Lubes", "Ford Bolita", "Ford Rondeau", "Gatti", "La Casa del Filtro", "Maugeri",
               "Moura", "Otro", "RSF", "Renault Alberdi", "Rombo Rondeau", "SXXI", "Sader", "San Pablo Filtros"]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###
    conexion = op.get_bind()
    usados = set(PROVEEDORES)
    for tabla in ("repuesto", "config_markup", "ingreso_stock"):
        usados |= {n for (n,) in conexion.execute(sa.text(f"SELECT DISTINCT proveedor FROM {tabla}")) if n}
    for nombre in sorted(usados, key=str.lower):
        conexion.execute(sa.text("INSERT INTO proveedor (nombre) VALUES (:n)"), {"n": nombre})


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proveedor')
    # ### end Alembic commands ###
