"""circular contable

Revision ID: ee5d2f7d0074
Revises: 8256d7862b35
Create Date: 2026-09-20 13:56:35.583939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee5d2f7d0074'
down_revision = '8256d7862b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compromiso_cierre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cierre_id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=120), nullable=False),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('a_dejar', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cierre_id'], ['cierre_mensual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cierre_mensual', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('caja_chica', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('banco', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('observaciones', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('link_circular', sa.String(length=300), nullable=True))

    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.drop_column('nota')

    with op.batch_alter_table('cierre_mensual', schema=None) as batch_op:
        batch_op.drop_column('link_circular')
        batch_op.drop_column('observaciones')
        batch_op.drop_column('banco')
        batch_op.drop_column('caja_chica')
        batch_op.drop_column('numero')

    op.drop_table('compromiso_cierre')
    # ### end Alembic commands ###
