"""vehiculo sin dueño

Revision ID: f1e27f36218d
Revises: a1749331c4e6
Create Date: 2026-09-18 22:06:16.403346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e27f36218d'
down_revision = 'a1749331c4e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculo', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculo', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
