"""auditoria de movimientos de stock

Revision ID: f3b694ad7abb
Revises: c308a1a344f8
Create Date: 2026-09-20 00:08:47.630249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b694ad7abb'
down_revision = 'c308a1a344f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimiento_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_resultante', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimiento_stock', schema=None) as batch_op:
        batch_op.drop_column('stock_resultante')

    # ### end Alembic commands ###
